compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
debug: true
num_processes: 2
use_cpu: false
machine_rank: 0
main_training_function: main
mixed_precision: bf16  

deepspeed_config:
  zero_stage: 3
  zero3_init_flag: true
  zero3_save_16bit_model: false
  offload_optimizer_device: none
  offload_param_device: none
  bf16: true
  fp16: false
  gradient_clipping: 1.0
  gradient_accumulation_steps: 1
  overlap_comm: true
  contiguous_gradients: true
