compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
mixed_precision: bf16 
deepspeed_config:
  zero_stage: 2
  gradient_accumulation_steps: 1
  offload_optimizer_device: none
  offload_param_device: none
  bf16: true    
  fp16: false   
  gradient_clipping: 1.0
  overlap_comm: true
  contiguous_gradients: true
machine_rank: 0
num_processes: 2
use_cpu: false
